<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitdcbb8e8b804aefe5d9aeaee4b41ef1e6
{
    public static $classMap = array (
        'Latte\\CompileException' => __DIR__ . '/..' . '/Latte/exceptions.php',
        'Latte\\Compiler' => __DIR__ . '/..' . '/Latte/Compiler/Compiler.php',
        'Latte\\Engine' => __DIR__ . '/..' . '/Latte/Engine.php',
        'Latte\\Helpers' => __DIR__ . '/..' . '/Latte/Helpers.php',
        'Latte\\HtmlNode' => __DIR__ . '/..' . '/Latte/Compiler/HtmlNode.php',
        'Latte\\ILoader' => __DIR__ . '/..' . '/compatibility.php',
        'Latte\\IMacro' => __DIR__ . '/..' . '/compatibility.php',
        'Latte\\Loader' => __DIR__ . '/..' . '/Latte/Loader.php',
        'Latte\\Loaders\\FileLoader' => __DIR__ . '/..' . '/Latte/Loaders/FileLoader.php',
        'Latte\\Loaders\\StringLoader' => __DIR__ . '/..' . '/Latte/Loaders/StringLoader.php',
        'Latte\\Macro' => __DIR__ . '/..' . '/Latte/Macro.php',
        'Latte\\MacroNode' => __DIR__ . '/..' . '/Latte/Compiler/MacroNode.php',
        'Latte\\MacroTokens' => __DIR__ . '/..' . '/Latte/Compiler/MacroTokens.php',
        'Latte\\Macros\\BlockMacros' => __DIR__ . '/..' . '/Latte/Macros/BlockMacros.php',
        'Latte\\Macros\\CoreMacros' => __DIR__ . '/..' . '/Latte/Macros/CoreMacros.php',
        'Latte\\Macros\\MacroSet' => __DIR__ . '/..' . '/Latte/Macros/MacroSet.php',
        'Latte\\Parser' => __DIR__ . '/..' . '/Latte/Compiler/Parser.php',
        'Latte\\PhpHelpers' => __DIR__ . '/..' . '/Latte/Compiler/PhpHelpers.php',
        'Latte\\PhpWriter' => __DIR__ . '/..' . '/Latte/Compiler/PhpWriter.php',
        'Latte\\RegexpException' => __DIR__ . '/..' . '/Latte/exceptions.php',
        'Latte\\RuntimeException' => __DIR__ . '/..' . '/Latte/exceptions.php',
        'Latte\\Runtime\\Blueprint' => __DIR__ . '/..' . '/Latte/Runtime/Blueprint.php',
        'Latte\\Runtime\\CachingIterator' => __DIR__ . '/..' . '/Latte/Runtime/CachingIterator.php',
        'Latte\\Runtime\\FilterExecutor' => __DIR__ . '/..' . '/Latte/Runtime/FilterExecutor.php',
        'Latte\\Runtime\\FilterInfo' => __DIR__ . '/..' . '/Latte/Runtime/FilterInfo.php',
        'Latte\\Runtime\\Filters' => __DIR__ . '/..' . '/Latte/Runtime/Filters.php',
        'Latte\\Runtime\\Html' => __DIR__ . '/..' . '/Latte/Runtime/Html.php',
        'Latte\\Runtime\\HtmlString' => __DIR__ . '/..' . '/Latte/Runtime/HtmlString.php',
        'Latte\\Runtime\\IHtmlString' => __DIR__ . '/..' . '/compatibility.php',
        'Latte\\Runtime\\ISnippetBridge' => __DIR__ . '/..' . '/compatibility.php',
        'Latte\\Runtime\\SnippetBridge' => __DIR__ . '/..' . '/Latte/Runtime/SnippetBridge.php',
        'Latte\\Runtime\\SnippetDriver' => __DIR__ . '/..' . '/Latte/Runtime/SnippetDriver.php',
        'Latte\\Runtime\\Template' => __DIR__ . '/..' . '/Latte/Runtime/Template.php',
        'Latte\\Strict' => __DIR__ . '/..' . '/Latte/Strict.php',
        'Latte\\Token' => __DIR__ . '/..' . '/Latte/Compiler/Token.php',
        'Latte\\TokenIterator' => __DIR__ . '/..' . '/Latte/Compiler/TokenIterator.php',
        'Latte\\Tokenizer' => __DIR__ . '/..' . '/Latte/Compiler/Tokenizer.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->classMap = ComposerStaticInitdcbb8e8b804aefe5d9aeaee4b41ef1e6::$classMap;

        }, null, ClassLoader::class);
    }
}
