<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitf5e0af5aa13d412face4cb4ea1965065
{
    public static $classMap = array (
        'Nette\\ArgumentOutOfRangeException' => __DIR__ . '/../Utils/exceptions.php',
        'Nette\\DeprecatedException' => __DIR__ . '/../Utils/exceptions.php',
        'Nette\\DirectoryNotFoundException' => __DIR__ . '/../Utils/exceptions.php',
        'Nette\\FileNotFoundException' => __DIR__ . '/../Utils/exceptions.php',
        'Nette\\IOException' => __DIR__ . '/../Utils/exceptions.php',
        'Nette\\InvalidArgumentException' => __DIR__ . '/../Utils/exceptions.php',
        'Nette\\InvalidStateException' => __DIR__ . '/../Utils/exceptions.php',
        'Nette\\Iterators\\CachingIterator' => __DIR__ . '/../Iterators/CachingIterator.php',
        'Nette\\Iterators\\Mapper' => __DIR__ . '/../Iterators/Mapper.php',
        'Nette\\Localization\\ITranslator' => __DIR__ . '/../Utils/ITranslator.php',
        'Nette\\MemberAccessException' => __DIR__ . '/../Utils/exceptions.php',
        'Nette\\NotImplementedException' => __DIR__ . '/../Utils/exceptions.php',
        'Nette\\NotSupportedException' => __DIR__ . '/../Utils/exceptions.php',
        'Nette\\OutOfRangeException' => __DIR__ . '/../Utils/exceptions.php',
        'Nette\\SmartObject' => __DIR__ . '/../Utils/SmartObject.php',
        'Nette\\StaticClass' => __DIR__ . '/../Utils/StaticClass.php',
        'Nette\\UnexpectedValueException' => __DIR__ . '/../Utils/exceptions.php',
        'Nette\\Utils\\ArrayHash' => __DIR__ . '/../Utils/ArrayHash.php',
        'Nette\\Utils\\ArrayList' => __DIR__ . '/../Utils/ArrayList.php',
        'Nette\\Utils\\Arrays' => __DIR__ . '/../Utils/Arrays.php',
        'Nette\\Utils\\AssertionException' => __DIR__ . '/../Utils/exceptions.php',
        'Nette\\Utils\\Callback' => __DIR__ . '/../Utils/Callback.php',
        'Nette\\Utils\\DateTime' => __DIR__ . '/../Utils/DateTime.php',
        'Nette\\Utils\\FileSystem' => __DIR__ . '/../Utils/FileSystem.php',
        'Nette\\Utils\\Helpers' => __DIR__ . '/../Utils/Helpers.php',
        'Nette\\Utils\\Html' => __DIR__ . '/../Utils/Html.php',
        'Nette\\Utils\\IHtmlString' => __DIR__ . '/../Utils/IHtmlString.php',
        'Nette\\Utils\\Image' => __DIR__ . '/../Utils/Image.php',
        'Nette\\Utils\\ImageException' => __DIR__ . '/../Utils/exceptions.php',
        'Nette\\Utils\\Json' => __DIR__ . '/../Utils/Json.php',
        'Nette\\Utils\\JsonException' => __DIR__ . '/../Utils/exceptions.php',
        'Nette\\Utils\\ObjectHelpers' => __DIR__ . '/../Utils/ObjectHelpers.php',
        'Nette\\Utils\\ObjectMixin' => __DIR__ . '/../Utils/ObjectMixin.php',
        'Nette\\Utils\\Paginator' => __DIR__ . '/../Utils/Paginator.php',
        'Nette\\Utils\\Random' => __DIR__ . '/../Utils/Random.php',
        'Nette\\Utils\\Reflection' => __DIR__ . '/../Utils/Reflection.php',
        'Nette\\Utils\\RegexpException' => __DIR__ . '/../Utils/exceptions.php',
        'Nette\\Utils\\Strings' => __DIR__ . '/../Utils/Strings.php',
        'Nette\\Utils\\UnknownImageFileException' => __DIR__ . '/../Utils/exceptions.php',
        'Nette\\Utils\\Validators' => __DIR__ . '/../Utils/Validators.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->classMap = ComposerStaticInitf5e0af5aa13d412face4cb4ea1965065::$classMap;

        }, null, ClassLoader::class);
    }
}
